story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.index, name="index"),
]

story6ppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story6.urls')),
]

story6/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    status = models.TextField()

story6/forms.py
from django import forms

class NewStatus(forms.Form):
    status = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class':'form-control'
            }
        ),
        label=""

        )

story6/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from . import models, forms

# Create your views here.

def index(request):
    new_status = forms.NewStatus()
    statuses = models.Status.objects.all()

    if request.method == 'POST':
        models.Status.objects.create(
            status = request.POST['status']
        )

        return HttpResponseRedirect("/")

    context = {
        'new_status':new_status,
        'statuses':statuses
    }

    return render(request, 'index.html', context)

story6/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title> Landing Page </title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
      <a class="navbar-brand header-title" href="{% url 'story6:index' %}"> Post-That </a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      </div>
    </nav>

    <div class="posting" align="center">
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          <h2> What are you thinking? </h2>
          {{new_status}}
        </div>
        <button class="btn btn-info" type="submit" name="button">Post that!</button>
      </form>
    </div>

    {% for element in statuses %}
      <div class="allStatus">
        <p id="text"> You posted: </p>
        <p> {{ element.status }} </p>
      </div>
    {% endfor %}
  </body>
</html>